name: xvega
channels:
  - conda-forge
dependencies:
# build dependencies
  - cmake
  - cxx-compiler
  - ninja
# host Dependencies
  - xproperty=0.12.0
  - nlohmann_json=3.12.0
# Test dependencies
  - doctest
